[book]
authors = ["Joseph Louthan"]
language = "en"
multilingual = false
src = "src"
title = "Theologicus"
description = "No pen, no words, no image can express to you the loveliness of my only, only Lord Jesus. - Samuel Rutherford"

[rust]
edition = "2021"

[build]
build-dir = "book"
create-missing = false

[preprocessor.index]

[preprocessor.links]

[output.html]
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/joelouthan/theologicus"
git-repository-icon = "fa-github"
no-section-label = true
edit-url-template = "https://github.com/joelouthan/book-theologicus/edit/master/guide/{path}"

# [output.wordcount] # uncomment to enable word count

[output.html.search]
limit-results = 25

[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding
