[build]
  command = "cargo install mdbook && cargo install mdbook-toc && export PATH=$PATH:`pwd`/bin && mdbook build"
  publish = "book"

[build.environment]
  RUSTUP_HOME = "./rustup"
  CARGO_HOME = "./cargo"

[build.cacheDirs]
  paths = ["./bin", "./rustup", "./cargo"]
